# Numpy_Assignment_2 :

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
Q1_Array = np.arange(10).reshape(2,5)
Q1_Array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
Q2_Array1 = np.arange(10).reshape(2,5)
Q2_Array2 = np.ones((2,5)).astype(int)
np.vstack((Q2_Array1,Q2_Array2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [14]:
Q3_Array1 = np.arange(10).reshape(2,5)
Q3_Array2 = np.ones((2,5)).astype(int)
np.hstack((Q3_Array1,Q3_Array2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
Q4_Array4 = np.arange(10).reshape(2,5)
Q4_Array4.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [24]:
Q5_Array = np.arange(15).reshape(1,3,5)
Q5_Array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [27]:
Q6_Array = np.arange(15)
Q6_Array.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [33]:
Q7_Array = np.arange(25).reshape(5,5)
np.square(Q7_Array)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [39]:
Q8_Array = np.arange(30).reshape(5,6)
Q8_Array.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [37]:
Q8_Array.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [42]:
np.median(Q8_Array)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [43]:
np.transpose(Q8_Array)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [69]:
Q12_Array = np.arange(2,18).reshape(4,4)
np.sum(np.diag(Q12_Array))

38

## Question:13

### Find the determinant of the previous array in Q12?

In [70]:
print(Q12_Array)
np.linalg.det(Q12_Array)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [72]:
Q14_Array = np.arange(1,20)
print(f'5th Percentile : {np.percentile(Q14_Array,5)}')
print(f'95th Percentile : {np.percentile(Q14_Array,95)}')

5th Percentile : 1.9
95th Percentile : 18.099999999999998


## Question:15

### How to find if a given array has any null values?

In [94]:
Q15_Array = np.arange(1,10).reshape(3,3)
Q15_Array[1] = np.nan
print(np.isnan(Q15_Array))

[[False False False]
 [False False False]
 [False False False]]
