# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [6]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
Null_Vector = np.zeros(10)
Null_Vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [8]:
Vector = np.arange(10,50)
Vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [9]:
Vector.shape

(40,)

5. Print the type of the previous array in question 3

In [10]:
Vector.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [15]:
print(f'Numpy Version : {np.__version__}')
print('Numpy Config :')
np.show_config()

Numpy Version : 1.19.3
Numpy Config :
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [16]:
Vector.ndim

1

8. Create a boolean array with all the True values

In [19]:
Boolean_Array = np.ones(5,dtype = bool)
Boolean_Array

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [12]:
Array_2D = np.array([(1,2,3), (4,5,6)])
print(f'Shape of the following Array : {Array_2D.shape}')
print(Array_2D)
#Second Way to Create 3D arrays
Array_2D = np.array(range(12)).reshape(3,4)
print(f'Shape of the following Array : {Array_2D.shape}')
print(Array_2D)

Shape of the following Array : (2, 3)
[[1 2 3]
 [4 5 6]]
Shape of the following Array : (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


10. Create a three dimensional array



In [13]:
Array_3D = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
print(f'Shape of the following Array : {Array_3D.shape}')
print(Array_3D)
#Second Way to Create 3D arrays
Array_3D = np.array(range(12)).reshape(2,2,3)
print(f'Shape of the following Array : {Array_3D.shape}')
print(Array_3D)

Shape of the following Array : (2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape of the following Array : (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [41]:
Vector_To_Be_Reversed = np.arange(10)
print(f"Array Before Reversing : {Vector_To_Be_Reversed}")
Vector_Reversed = Vector_To_Be_Reversed[::-1]
print(f'Vector After Reversing : {Vector_Reversed}')

Array Before Reversing : [0 1 2 3 4 5 6 7 8 9]
Vector After Reversing : [9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [42]:
Null_Vector_Except_5th_element = np.zeros(10)
Null_Vector_Except_5th_element[4] = 1
Null_Vector_Except_5th_element

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [43]:
Identity_Matrix = np.eye(3,3)
Identity_Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [19]:
arr = np.array([1, 2, 3, 4, 5]) 
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [3]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [4]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [15]:
arr[arr % 2 != 0]

array([1, 3, 5])

18. Replace all odd numbers to -1 from previous array

In [20]:
print (f'Array Before Replacing : {arr}')
arr[arr % 2 != 0] = -1
print (f'Array After Replacing : {arr}')

Array Before Replacing : [1 2 3 4 5]
Array After Replacing : [-1  2 -1  4 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [8]:
arr = np.arange(10)
arr[5:9] = 12 # arr[[5,6,7,8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [35]:
One_Border_Array = np.ones((5,5))
One_Border_Array[1:-1,1:-1] = 0
One_Border_Array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [38]:
arr2d = np.array([[1, 2, 3],

                [4, 5, 6], 

                [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [45]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f'before Changing : \n{arr3d}')
arr3d[0] = 64
print(f'After Changing : \n{arr3d}')

before Changing : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
After Changing : 
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [55]:
Array_2D = np.arange(10).reshape(2,5)
print(f'Full Array : \n{Array_2D}')
print(f'Sliced Array : {Array_2D[0]}')

Full Array : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
Sliced Array : [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [58]:
Array_2D = np.arange(10).reshape(2,5)
print(f'Full Array : \n{Array_2D}')
print(f'Sliced Array : {Array_2D[1]}')

Full Array : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
Sliced Array : [5 6 7 8 9]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [62]:
Array_2D = np.arange(10).reshape(2,5)
print(f'Full Array : \n{Array_2D}')
print(f'Sliced Array : {Array_2D[:2,2]}')

Full Array : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
Sliced Array : [2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [67]:
Random_Array = np.random.randn(10,10)
print(f'Min Value : {np.min(Random_Array)}')
print(f'Max Value : {np.max(Random_Array)}')
print(f'Array Generated : \n{Random_Array}')

Min Value : -2.6968034436606114
Max Value : 2.7780745677115024
Array Generated : 
[[-0.28499869  0.17007461 -0.62607019  0.33693952 -1.21295329  0.29329216
   1.03995505  0.41630136 -0.09427751  0.62187647]
 [ 0.16366023  1.03049654 -0.01406733  1.16501209 -0.59943832  0.83209722
  -1.19718589 -0.19133201 -0.03668265 -0.55049724]
 [ 0.43506321 -0.14246587  0.02694659 -0.43204929 -1.37106141 -0.06260847
   0.59690626 -1.00924132  1.07660943  0.60572206]
 [-0.47712522 -0.15805555  1.02022883  0.78293606 -0.88851181 -0.02499
   1.53572528  1.65258924  2.77807457 -1.00529186]
 [-0.72373186  1.18732362 -0.31752399 -1.34707998  0.17488356  0.60360917
  -0.58643992  1.49116997  0.06165764  0.67132178]
 [-0.54195852 -1.08422425  0.17925261 -1.25877361 -1.33673806  0.29769174
  -0.58156387 -1.32516532  0.47463128  0.05200345]
 [-0.95585047  0.13045663 -0.75886587  0.70818419 -0.41703003  0.41635765
  -0.70377969  0.40067463 -1.27107608  0.15312429]
 [-0.23050407 -0.92714951 -0.35670248 -0.23522

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [70]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.flatnonzero(np.isin(a,b))

array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [74]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'Will']

array([[ 0.89677085, -0.98536815,  0.62454307, -1.00074957],
       [ 0.26586816,  1.75788419, -1.13621691,  0.32914537],
       [-0.87168322, -0.03250819, -0.08842842,  0.30408563],
       [ 0.53897674, -0.92479122,  0.43245252,  1.02988226],
       [ 1.32935747, -0.45157939, -0.48180541, -0.51374278]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [104]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names != 'Will') & (names != 'Joe')]

array([[-0.48491754,  0.69590032,  0.59503715, -0.81926843],
       [-0.71912024, -1.16869661,  0.29725643,  0.72709824]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [83]:
Array_2D_Q31 = np.arange(1,16).reshape(5,3)
Array_2D_Q31

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [94]:
Q32_array = np.arange(1,17).reshape(2,2,4)
Q32_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [95]:
np.swapaxes(Q32_array,1,0)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [7]:
Q34_array = np.array([.1, 1, 0.2, 0, .5, .15, 12, 16, 9, 10])
print(f'Before : \n {Q34_array}')
# Q34_array[ np.sqrt(Q34_array) < 0.5 ] = 0
print(f'After : \n {np.where((np.sqrt(Q34_array) < 0.5) , 0 ,Q34_array )}')

Before : 
 [ 0.1   1.    0.2   0.    0.5   0.15 12.   16.    9.   10.  ]
After : 
 [ 0.   1.   0.   0.   0.5  0.  12.  16.   9.  10. ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [10]:
Q35_array_1 = np.random.randn(12)
Q35_array_2 = np.random.randn(12)
print(f'Array 1 : \n{Q35_array_1}')
print(f'Array 2 : \n{Q35_array_2}')
print(f'Resultant Array : \n{np.maximum(Q35_array_1,Q35_array_2)}')

Array 1 : 
[-0.14488569 -1.37495651  0.78047381 -0.32985341  0.09273658  1.4416805
  0.135907    0.92814143  0.65030148 -0.25815137  0.4897725   0.35737481]
Array 2 : 
[-0.37344678 -1.80332504 -1.91850727  1.19754407 -0.27782816  0.64663411
  0.88348439 -0.18825528 -1.95507505  0.47907438  1.04479493 -0.80758364]
Resultant Array : 
[-0.14488569 -1.37495651  0.78047381  1.19754407  0.09273658  1.4416805
  0.88348439  0.92814143  0.65030148  0.47907438  1.04479493  0.35737481]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
sorted(np.unique(names))

['Bob', 'Joe', 'Will']

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [21]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [40]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sampleArray[:,1] = newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [41]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [45]:
Q40_Array = np.random.randn(20)
Q40_Array.cumsum()

array([1.78148819, 2.73374796, 3.95204392, 3.90760318, 3.77370346,
       3.88781943, 4.02352693, 3.97345171, 3.65724736, 3.60001396,
       4.55138957, 4.66175614, 4.7407714 , 5.43648574, 7.14865023,
       7.8436188 , 6.98995775, 7.62962658, 9.02989624, 8.49908842])